# training settings
train:
    # fold setting
    fold_num: 10
    fold_type: skf
    # resampling setting
    # sampling_type: pos
    sampling_type: none
    os_lim: 1000000
    sampling_random_state: 71
    pos_t: 0
    neg_t: 0
    # single model setting
    single_model: False
    # feature setting
    all_features: False
    # feature selection setting
    feature_selection: False
    feature_select_path: 'importances/'
    metric: 'split_cov'
    feature_topk: 150

# lightGBM parameters
lgbm_params:
    boosting: gbdt
    boost_from_average: False
    verbose: -1
    random_state: 71
    objective: binary
    metric: binary_logloss
    # metric: auc
    learning_rate: 0.01
    # num_leaves: 256
    num_leaves: 13
    max_depth: -1
    subsample: 0.4
    bagging_freq: 5
    colsample_bytree: 0.05
    min_data_in_leaf: 60
    min_sum_hessian_in_leaf: 10.0
    lambda_l1: 0.1
    min_data_per_group: 1
    cat_smooth: 750
    cat_l2: 100
    max_cat_to_onehot: 10

features:
    - ID_code
    - f010_non_uniq_masked_var_0
    - f010_non_uniq_masked_var_1
    - f010_non_uniq_masked_var_10
    - f010_non_uniq_masked_var_100
    - f010_non_uniq_masked_var_101
    - f010_non_uniq_masked_var_102
    - f010_non_uniq_masked_var_103
    - f010_non_uniq_masked_var_104
    - f010_non_uniq_masked_var_105
    - f010_non_uniq_masked_var_106
    - f010_non_uniq_masked_var_107
    - f010_non_uniq_masked_var_108
    - f010_non_uniq_masked_var_109
    - f010_non_uniq_masked_var_11
    - f010_non_uniq_masked_var_110
    - f010_non_uniq_masked_var_111
    - f010_non_uniq_masked_var_112
    - f010_non_uniq_masked_var_113
    - f010_non_uniq_masked_var_114
    - f010_non_uniq_masked_var_115
    - f010_non_uniq_masked_var_116
    - f010_non_uniq_masked_var_117
    - f010_non_uniq_masked_var_118
    - f010_non_uniq_masked_var_119
    - f010_non_uniq_masked_var_12
    - f010_non_uniq_masked_var_120
    - f010_non_uniq_masked_var_121
    - f010_non_uniq_masked_var_122
    - f010_non_uniq_masked_var_123
    - f010_non_uniq_masked_var_124
    - f010_non_uniq_masked_var_125
    - f010_non_uniq_masked_var_126
    - f010_non_uniq_masked_var_127
    - f010_non_uniq_masked_var_128
    - f010_non_uniq_masked_var_129
    - f010_non_uniq_masked_var_13
    - f010_non_uniq_masked_var_130
    - f010_non_uniq_masked_var_131
    - f010_non_uniq_masked_var_132
    - f010_non_uniq_masked_var_133
    - f010_non_uniq_masked_var_134
    - f010_non_uniq_masked_var_135
    - f010_non_uniq_masked_var_136
    - f010_non_uniq_masked_var_137
    - f010_non_uniq_masked_var_138
    - f010_non_uniq_masked_var_139
    - f010_non_uniq_masked_var_14
    - f010_non_uniq_masked_var_140
    - f010_non_uniq_masked_var_141
    - f010_non_uniq_masked_var_142
    - f010_non_uniq_masked_var_143
    - f010_non_uniq_masked_var_144
    - f010_non_uniq_masked_var_145
    - f010_non_uniq_masked_var_146
    - f010_non_uniq_masked_var_147
    - f010_non_uniq_masked_var_148
    - f010_non_uniq_masked_var_149
    - f010_non_uniq_masked_var_15
    - f010_non_uniq_masked_var_150
    - f010_non_uniq_masked_var_151
    - f010_non_uniq_masked_var_152
    - f010_non_uniq_masked_var_153
    - f010_non_uniq_masked_var_154
    - f010_non_uniq_masked_var_155
    - f010_non_uniq_masked_var_156
    - f010_non_uniq_masked_var_157
    - f010_non_uniq_masked_var_158
    - f010_non_uniq_masked_var_159
    - f010_non_uniq_masked_var_16
    - f010_non_uniq_masked_var_160
    - f010_non_uniq_masked_var_161
    - f010_non_uniq_masked_var_162
    - f010_non_uniq_masked_var_163
    - f010_non_uniq_masked_var_164
    - f010_non_uniq_masked_var_165
    - f010_non_uniq_masked_var_166
    - f010_non_uniq_masked_var_167
    - f010_non_uniq_masked_var_168
    - f010_non_uniq_masked_var_169
    - f010_non_uniq_masked_var_17
    - f010_non_uniq_masked_var_170
    - f010_non_uniq_masked_var_171
    - f010_non_uniq_masked_var_172
    - f010_non_uniq_masked_var_173
    - f010_non_uniq_masked_var_174
    - f010_non_uniq_masked_var_175
    - f010_non_uniq_masked_var_176
    - f010_non_uniq_masked_var_177
    - f010_non_uniq_masked_var_178
    - f010_non_uniq_masked_var_179
    - f010_non_uniq_masked_var_18
    - f010_non_uniq_masked_var_180
    - f010_non_uniq_masked_var_181
    - f010_non_uniq_masked_var_182
    - f010_non_uniq_masked_var_183
    - f010_non_uniq_masked_var_184
    - f010_non_uniq_masked_var_185
    - f010_non_uniq_masked_var_186
    - f010_non_uniq_masked_var_187
    - f010_non_uniq_masked_var_188
    - f010_non_uniq_masked_var_189
    - f010_non_uniq_masked_var_19
    - f010_non_uniq_masked_var_190
    - f010_non_uniq_masked_var_191
    - f010_non_uniq_masked_var_192
    - f010_non_uniq_masked_var_193
    - f010_non_uniq_masked_var_194
    - f010_non_uniq_masked_var_195
    - f010_non_uniq_masked_var_196
    - f010_non_uniq_masked_var_197
    - f010_non_uniq_masked_var_198
    - f010_non_uniq_masked_var_199
    - f010_non_uniq_masked_var_2
    - f010_non_uniq_masked_var_20
    - f010_non_uniq_masked_var_21
    - f010_non_uniq_masked_var_22
    - f010_non_uniq_masked_var_23
    - f010_non_uniq_masked_var_24
    - f010_non_uniq_masked_var_25
    - f010_non_uniq_masked_var_26
    - f010_non_uniq_masked_var_27
    - f010_non_uniq_masked_var_28
    - f010_non_uniq_masked_var_29
    - f010_non_uniq_masked_var_3
    - f010_non_uniq_masked_var_30
    - f010_non_uniq_masked_var_31
    - f010_non_uniq_masked_var_32
    - f010_non_uniq_masked_var_33
    - f010_non_uniq_masked_var_34
    - f010_non_uniq_masked_var_35
    - f010_non_uniq_masked_var_36
    - f010_non_uniq_masked_var_37
    - f010_non_uniq_masked_var_38
    - f010_non_uniq_masked_var_39
    - f010_non_uniq_masked_var_4
    - f010_non_uniq_masked_var_40
    - f010_non_uniq_masked_var_41
    - f010_non_uniq_masked_var_42
    - f010_non_uniq_masked_var_43
    - f010_non_uniq_masked_var_44
    - f010_non_uniq_masked_var_45
    - f010_non_uniq_masked_var_46
    - f010_non_uniq_masked_var_47
    - f010_non_uniq_masked_var_48
    - f010_non_uniq_masked_var_49
    - f010_non_uniq_masked_var_5
    - f010_non_uniq_masked_var_50
    - f010_non_uniq_masked_var_51
    - f010_non_uniq_masked_var_52
    - f010_non_uniq_masked_var_53
    - f010_non_uniq_masked_var_54
    - f010_non_uniq_masked_var_55
    - f010_non_uniq_masked_var_56
    - f010_non_uniq_masked_var_57
    - f010_non_uniq_masked_var_58
    - f010_non_uniq_masked_var_59
    - f010_non_uniq_masked_var_6
    - f010_non_uniq_masked_var_60
    - f010_non_uniq_masked_var_61
    - f010_non_uniq_masked_var_62
    - f010_non_uniq_masked_var_63
    - f010_non_uniq_masked_var_64
    - f010_non_uniq_masked_var_65
    - f010_non_uniq_masked_var_66
    - f010_non_uniq_masked_var_67
    - f010_non_uniq_masked_var_68
    - f010_non_uniq_masked_var_69
    - f010_non_uniq_masked_var_7
    - f010_non_uniq_masked_var_70
    - f010_non_uniq_masked_var_71
    - f010_non_uniq_masked_var_72
    - f010_non_uniq_masked_var_73
    - f010_non_uniq_masked_var_74
    - f010_non_uniq_masked_var_75
    - f010_non_uniq_masked_var_76
    - f010_non_uniq_masked_var_77
    - f010_non_uniq_masked_var_78
    - f010_non_uniq_masked_var_79
    - f010_non_uniq_masked_var_8
    - f010_non_uniq_masked_var_80
    - f010_non_uniq_masked_var_81
    - f010_non_uniq_masked_var_82
    - f010_non_uniq_masked_var_83
    - f010_non_uniq_masked_var_84
    - f010_non_uniq_masked_var_85
    - f010_non_uniq_masked_var_86
    - f010_non_uniq_masked_var_87
    - f010_non_uniq_masked_var_88
    - f010_non_uniq_masked_var_89
    - f010_non_uniq_masked_var_9
    - f010_non_uniq_masked_var_90
    - f010_non_uniq_masked_var_91
    - f010_non_uniq_masked_var_92
    - f010_non_uniq_masked_var_93
    - f010_non_uniq_masked_var_94
    - f010_non_uniq_masked_var_95
    - f010_non_uniq_masked_var_96
    - f010_non_uniq_masked_var_97
    - f010_non_uniq_masked_var_98
    - f010_non_uniq_masked_var_99
