# training settings
train:
    # fold setting
    fold_num: 10
    fold_type: skf
    # resampling setting
    # sampling_type: pos
    sampling_type: none
    os_lim: 1000000
    sampling_random_state: 71
    pos_t: 0
    neg_t: 0
    # single model setting
    single_model: False
    # feature setting
    all_features: False
    # feature selection setting
    feature_selection: False
    feature_select_path: 'importances/'
    metric: 'split_cov'
    feature_topk: 150

# lightGBM parameters
lgbm_params:
    boosting: gbdt
    boost_from_average: False
    verbose: -1
    random_state: 71
    objective: binary
    metric: binary_logloss
    # metric: auc
    learning_rate: 0.001
    #num_leaves: 7
    num_leaves: 3
    max_depth: -1
    subsample: 0.4
    bagging_freq: 1
    colsample_bytree: 0.1
    min_data_in_leaf: 60
    min_sum_hessian_in_leaf: 10.0
    lambda_l1: 0.1
    #    num_iterations: 10415

features:
    - ID_code
    - vicens_92374
    - guchio_92396
    - f033_real_count_encoding_var_0
    - f033_real_count_encoding_var_1
    - f033_real_count_encoding_var_2
    - f033_real_count_encoding_var_3
    - f033_real_count_encoding_var_4
    - f033_real_count_encoding_var_5
    - f033_real_count_encoding_var_6
    - f033_real_count_encoding_var_7
    - f033_real_count_encoding_var_8
    - f033_real_count_encoding_var_9
    - f033_real_count_encoding_var_10
    - f033_real_count_encoding_var_11
    - f033_real_count_encoding_var_12
    - f033_real_count_encoding_var_13
    - f033_real_count_encoding_var_14
    - f033_real_count_encoding_var_15
    - f033_real_count_encoding_var_16
    - f033_real_count_encoding_var_17
    - f033_real_count_encoding_var_18
    - f033_real_count_encoding_var_19
    - f033_real_count_encoding_var_20
    - f033_real_count_encoding_var_21
    - f033_real_count_encoding_var_22
    - f033_real_count_encoding_var_23
    - f033_real_count_encoding_var_24
    - f033_real_count_encoding_var_25
    - f033_real_count_encoding_var_26
    - f033_real_count_encoding_var_27
    - f033_real_count_encoding_var_28
    - f033_real_count_encoding_var_29
    - f033_real_count_encoding_var_30
    - f033_real_count_encoding_var_31
    - f033_real_count_encoding_var_32
    - f033_real_count_encoding_var_33
    - f033_real_count_encoding_var_34
    - f033_real_count_encoding_var_35
    - f033_real_count_encoding_var_36
    - f033_real_count_encoding_var_37
    - f033_real_count_encoding_var_38
    - f033_real_count_encoding_var_39
    - f033_real_count_encoding_var_40
    - f033_real_count_encoding_var_41
    - f033_real_count_encoding_var_42
    - f033_real_count_encoding_var_43
    - f033_real_count_encoding_var_44
    - f033_real_count_encoding_var_45
    - f033_real_count_encoding_var_46
    - f033_real_count_encoding_var_47
    - f033_real_count_encoding_var_48
    - f033_real_count_encoding_var_49
    - f033_real_count_encoding_var_50
    - f033_real_count_encoding_var_51
    - f033_real_count_encoding_var_52
    - f033_real_count_encoding_var_53
    - f033_real_count_encoding_var_54
    - f033_real_count_encoding_var_55
    - f033_real_count_encoding_var_56
    - f033_real_count_encoding_var_57
    - f033_real_count_encoding_var_58
    - f033_real_count_encoding_var_59
    - f033_real_count_encoding_var_60
    - f033_real_count_encoding_var_61
    - f033_real_count_encoding_var_62
    - f033_real_count_encoding_var_63
    - f033_real_count_encoding_var_64
    - f033_real_count_encoding_var_65
    - f033_real_count_encoding_var_66
    - f033_real_count_encoding_var_67
    - f033_real_count_encoding_var_68
    - f033_real_count_encoding_var_69
    - f033_real_count_encoding_var_70
    - f033_real_count_encoding_var_71
    - f033_real_count_encoding_var_72
    - f033_real_count_encoding_var_73
    - f033_real_count_encoding_var_74
    - f033_real_count_encoding_var_75
    - f033_real_count_encoding_var_76
    - f033_real_count_encoding_var_77
    - f033_real_count_encoding_var_78
    - f033_real_count_encoding_var_79
    - f033_real_count_encoding_var_80
    - f033_real_count_encoding_var_81
    - f033_real_count_encoding_var_82
    - f033_real_count_encoding_var_83
    - f033_real_count_encoding_var_84
    - f033_real_count_encoding_var_85
    - f033_real_count_encoding_var_86
    - f033_real_count_encoding_var_87
    - f033_real_count_encoding_var_88
    - f033_real_count_encoding_var_89
    - f033_real_count_encoding_var_90
    - f033_real_count_encoding_var_91
    - f033_real_count_encoding_var_92
    - f033_real_count_encoding_var_93
    - f033_real_count_encoding_var_94
    - f033_real_count_encoding_var_95
    - f033_real_count_encoding_var_96
    - f033_real_count_encoding_var_97
    - f033_real_count_encoding_var_98
    - f033_real_count_encoding_var_99
    - f033_real_count_encoding_var_100
    - f033_real_count_encoding_var_101
    - f033_real_count_encoding_var_102
    - f033_real_count_encoding_var_103
    - f033_real_count_encoding_var_104
    - f033_real_count_encoding_var_105
    - f033_real_count_encoding_var_106
    - f033_real_count_encoding_var_107
    - f033_real_count_encoding_var_108
    - f033_real_count_encoding_var_109
    - f033_real_count_encoding_var_110
    - f033_real_count_encoding_var_111
    - f033_real_count_encoding_var_112
    - f033_real_count_encoding_var_113
    - f033_real_count_encoding_var_114
    - f033_real_count_encoding_var_115
    - f033_real_count_encoding_var_116
    - f033_real_count_encoding_var_117
    - f033_real_count_encoding_var_118
    - f033_real_count_encoding_var_119
    - f033_real_count_encoding_var_120
    - f033_real_count_encoding_var_121
    - f033_real_count_encoding_var_122
    - f033_real_count_encoding_var_123
    - f033_real_count_encoding_var_124
    - f033_real_count_encoding_var_125
    - f033_real_count_encoding_var_126
    - f033_real_count_encoding_var_127
    - f033_real_count_encoding_var_128
    - f033_real_count_encoding_var_129
    - f033_real_count_encoding_var_130
    - f033_real_count_encoding_var_131
    - f033_real_count_encoding_var_132
    - f033_real_count_encoding_var_133
    - f033_real_count_encoding_var_134
    - f033_real_count_encoding_var_135
    - f033_real_count_encoding_var_136
    - f033_real_count_encoding_var_137
    - f033_real_count_encoding_var_138
    - f033_real_count_encoding_var_139
    - f033_real_count_encoding_var_140
    - f033_real_count_encoding_var_141
    - f033_real_count_encoding_var_142
    - f033_real_count_encoding_var_143
    - f033_real_count_encoding_var_144
    - f033_real_count_encoding_var_145
    - f033_real_count_encoding_var_146
    - f033_real_count_encoding_var_147
    - f033_real_count_encoding_var_148
    - f033_real_count_encoding_var_149
    - f033_real_count_encoding_var_150
    - f033_real_count_encoding_var_151
    - f033_real_count_encoding_var_152
    - f033_real_count_encoding_var_153
    - f033_real_count_encoding_var_154
    - f033_real_count_encoding_var_155
    - f033_real_count_encoding_var_156
    - f033_real_count_encoding_var_157
    - f033_real_count_encoding_var_158
    - f033_real_count_encoding_var_159
    - f033_real_count_encoding_var_160
    - f033_real_count_encoding_var_161
    - f033_real_count_encoding_var_162
    - f033_real_count_encoding_var_163
    - f033_real_count_encoding_var_164
    - f033_real_count_encoding_var_165
    - f033_real_count_encoding_var_166
    - f033_real_count_encoding_var_167
    - f033_real_count_encoding_var_168
    - f033_real_count_encoding_var_169
    - f033_real_count_encoding_var_170
    - f033_real_count_encoding_var_171
    - f033_real_count_encoding_var_172
    - f033_real_count_encoding_var_173
    - f033_real_count_encoding_var_174
    - f033_real_count_encoding_var_175
    - f033_real_count_encoding_var_176
    - f033_real_count_encoding_var_177
    - f033_real_count_encoding_var_178
    - f033_real_count_encoding_var_179
    - f033_real_count_encoding_var_180
    - f033_real_count_encoding_var_181
    - f033_real_count_encoding_var_182
    - f033_real_count_encoding_var_183
    - f033_real_count_encoding_var_184
    - f033_real_count_encoding_var_185
    - f033_real_count_encoding_var_186
    - f033_real_count_encoding_var_187
    - f033_real_count_encoding_var_188
    - f033_real_count_encoding_var_189
    - f033_real_count_encoding_var_190
    - f033_real_count_encoding_var_191
    - f033_real_count_encoding_var_192
    - f033_real_count_encoding_var_193
    - f033_real_count_encoding_var_194
    - f033_real_count_encoding_var_195
    - f033_real_count_encoding_var_196
    - f033_real_count_encoding_var_197
    - f033_real_count_encoding_var_198
    - f033_real_count_encoding_var_199
