features:
    - ID_code
    - f006_uniq_cnt_var_0
    - f006_uniq_cnt_var_1
    - f006_uniq_cnt_var_10
    - f006_uniq_cnt_var_100
    - f006_uniq_cnt_var_101
    - f006_uniq_cnt_var_102
    - f006_uniq_cnt_var_103
    - f006_uniq_cnt_var_104
    - f006_uniq_cnt_var_105
    - f006_uniq_cnt_var_106
    - f006_uniq_cnt_var_107
    - f006_uniq_cnt_var_108
    - f006_uniq_cnt_var_109
    - f006_uniq_cnt_var_11
    - f006_uniq_cnt_var_110
    - f006_uniq_cnt_var_111
    - f006_uniq_cnt_var_112
    - f006_uniq_cnt_var_113
    - f006_uniq_cnt_var_114
    - f006_uniq_cnt_var_115
    - f006_uniq_cnt_var_116
    - f006_uniq_cnt_var_117
    - f006_uniq_cnt_var_118
    - f006_uniq_cnt_var_119
    - f006_uniq_cnt_var_12
    - f006_uniq_cnt_var_120
    - f006_uniq_cnt_var_121
    - f006_uniq_cnt_var_122
    - f006_uniq_cnt_var_123
    - f006_uniq_cnt_var_124
    - f006_uniq_cnt_var_125
    - f006_uniq_cnt_var_126
    - f006_uniq_cnt_var_127
    - f006_uniq_cnt_var_128
    - f006_uniq_cnt_var_129
    - f006_uniq_cnt_var_13
    - f006_uniq_cnt_var_130
    - f006_uniq_cnt_var_131
    - f006_uniq_cnt_var_132
    - f006_uniq_cnt_var_133
    - f006_uniq_cnt_var_134
    - f006_uniq_cnt_var_135
    - f006_uniq_cnt_var_136
    - f006_uniq_cnt_var_137
    - f006_uniq_cnt_var_138
    - f006_uniq_cnt_var_139
    - f006_uniq_cnt_var_14
    - f006_uniq_cnt_var_140
    - f006_uniq_cnt_var_141
    - f006_uniq_cnt_var_142
    - f006_uniq_cnt_var_143
    - f006_uniq_cnt_var_144
    - f006_uniq_cnt_var_145
    - f006_uniq_cnt_var_146
    - f006_uniq_cnt_var_147
    - f006_uniq_cnt_var_148
    - f006_uniq_cnt_var_149
    - f006_uniq_cnt_var_15
    - f006_uniq_cnt_var_150
    - f006_uniq_cnt_var_151
    - f006_uniq_cnt_var_152
    - f006_uniq_cnt_var_153
    - f006_uniq_cnt_var_154
    - f006_uniq_cnt_var_155
    - f006_uniq_cnt_var_156
    - f006_uniq_cnt_var_157
    - f006_uniq_cnt_var_158
    - f006_uniq_cnt_var_159
    - f006_uniq_cnt_var_16
    - f006_uniq_cnt_var_160
    - f006_uniq_cnt_var_161
    - f006_uniq_cnt_var_162
    - f006_uniq_cnt_var_163
    - f006_uniq_cnt_var_164
    - f006_uniq_cnt_var_165
    - f006_uniq_cnt_var_166
    - f006_uniq_cnt_var_167
    - f006_uniq_cnt_var_168
    - f006_uniq_cnt_var_169
    - f006_uniq_cnt_var_17
    - f006_uniq_cnt_var_170
    - f006_uniq_cnt_var_171
    - f006_uniq_cnt_var_172
    - f006_uniq_cnt_var_173
    - f006_uniq_cnt_var_174
    - f006_uniq_cnt_var_175
    - f006_uniq_cnt_var_176
    - f006_uniq_cnt_var_177
    - f006_uniq_cnt_var_178
    - f006_uniq_cnt_var_179
    - f006_uniq_cnt_var_18
    - f006_uniq_cnt_var_180
    - f006_uniq_cnt_var_181
    - f006_uniq_cnt_var_182
    - f006_uniq_cnt_var_183
    - f006_uniq_cnt_var_184
    - f006_uniq_cnt_var_185
    - f006_uniq_cnt_var_186
    - f006_uniq_cnt_var_187
    - f006_uniq_cnt_var_188
    - f006_uniq_cnt_var_189
    - f006_uniq_cnt_var_19
    - f006_uniq_cnt_var_190
    - f006_uniq_cnt_var_191
    - f006_uniq_cnt_var_192
    - f006_uniq_cnt_var_193
    - f006_uniq_cnt_var_194
    - f006_uniq_cnt_var_195
    - f006_uniq_cnt_var_196
    - f006_uniq_cnt_var_197
    - f006_uniq_cnt_var_198
    - f006_uniq_cnt_var_199
    - f006_uniq_cnt_var_2
    - f006_uniq_cnt_var_20
    - f006_uniq_cnt_var_21
    - f006_uniq_cnt_var_22
    - f006_uniq_cnt_var_23
    - f006_uniq_cnt_var_24
    - f006_uniq_cnt_var_25
    - f006_uniq_cnt_var_26
    - f006_uniq_cnt_var_27
    - f006_uniq_cnt_var_28
    - f006_uniq_cnt_var_29
    - f006_uniq_cnt_var_3
    - f006_uniq_cnt_var_30
    - f006_uniq_cnt_var_31
    - f006_uniq_cnt_var_32
    - f006_uniq_cnt_var_33
    - f006_uniq_cnt_var_34
    - f006_uniq_cnt_var_35
    - f006_uniq_cnt_var_36
    - f006_uniq_cnt_var_37
    - f006_uniq_cnt_var_38
    - f006_uniq_cnt_var_39
    - f006_uniq_cnt_var_4
    - f006_uniq_cnt_var_40
    - f006_uniq_cnt_var_41
    - f006_uniq_cnt_var_42
    - f006_uniq_cnt_var_43
    - f006_uniq_cnt_var_44
    - f006_uniq_cnt_var_45
    - f006_uniq_cnt_var_46
    - f006_uniq_cnt_var_47
    - f006_uniq_cnt_var_48
    - f006_uniq_cnt_var_49
    - f006_uniq_cnt_var_5
    - f006_uniq_cnt_var_50
    - f006_uniq_cnt_var_51
    - f006_uniq_cnt_var_52
    - f006_uniq_cnt_var_53
    - f006_uniq_cnt_var_54
    - f006_uniq_cnt_var_55
    - f006_uniq_cnt_var_56
    - f006_uniq_cnt_var_57
    - f006_uniq_cnt_var_58
    - f006_uniq_cnt_var_59
    - f006_uniq_cnt_var_6
    - f006_uniq_cnt_var_60
    - f006_uniq_cnt_var_61
    - f006_uniq_cnt_var_62
    - f006_uniq_cnt_var_63
    - f006_uniq_cnt_var_64
    - f006_uniq_cnt_var_65
    - f006_uniq_cnt_var_66
    - f006_uniq_cnt_var_67
    - f006_uniq_cnt_var_68
    - f006_uniq_cnt_var_69
    - f006_uniq_cnt_var_7
    - f006_uniq_cnt_var_70
    - f006_uniq_cnt_var_71
    - f006_uniq_cnt_var_72
    - f006_uniq_cnt_var_73
    - f006_uniq_cnt_var_74
    - f006_uniq_cnt_var_75
    - f006_uniq_cnt_var_76
    - f006_uniq_cnt_var_77
    - f006_uniq_cnt_var_78
    - f006_uniq_cnt_var_79
    - f006_uniq_cnt_var_8
    - f006_uniq_cnt_var_80
    - f006_uniq_cnt_var_81
    - f006_uniq_cnt_var_82
    - f006_uniq_cnt_var_83
    - f006_uniq_cnt_var_84
    - f006_uniq_cnt_var_85
    - f006_uniq_cnt_var_86
    - f006_uniq_cnt_var_87
    - f006_uniq_cnt_var_88
    - f006_uniq_cnt_var_89
    - f006_uniq_cnt_var_9
    - f006_uniq_cnt_var_90
    - f006_uniq_cnt_var_91
    - f006_uniq_cnt_var_92
    - f006_uniq_cnt_var_93
    - f006_uniq_cnt_var_94
    - f006_uniq_cnt_var_95
    - f006_uniq_cnt_var_96
    - f006_uniq_cnt_var_97
    - f006_uniq_cnt_var_98
    - f006_uniq_cnt_var_99
